redis:
  image: redis:3.0.7-alpine
  ports:
      - "6379"
pybelt:
  build: .
  links:
    - redis
  command: sleep 1000000
  volumes:
    - ./:/app
    - ~/.aws:/.aws
  environment:
    - REDIS_HOST=redis